#!/bin/bash

# Toggles state of HDFS tunnel
# (See notes in hdfs-readme.txt for more information)

HDFS_CMD="hdfs dfs"
HDFS_PORT=2600
HDFS_HOST=rodin.med.cornell.edu


# check for user name
[ -n "$HDFS_USER" ] || { echo "$(basename $0) > HDFS_USER environment variable is undefined"; exit 1; }


# the final grep from command chain returns 0 if matches were found, o.w. 1
# with the "!" operator, this is negated
PROCESS=$(! ps -u $USER -eo pid,command |grep 'ssh'|grep $HDFS_HOST|grep -- '-ND')
ENABLED=$?
echo "ENABLED: " $ENABLED


function usage () {
    echo "Toggle / check state of HDFS tunnel"
    echo "Usage: $(basename $0) [options]"
    echo "       -t toggle (default, if no flags specified)"
    echo "       -c check"
    echo "       -h display help"
    exit 2
}

# process flags 
while getopts  "tch" flag
do
    #echo "$flag" $OPTIND $OPTARG
    ( [ "$flag" == "h" ] || [ "$flag" == ":" ] || [ "$flag" == "?" ] ) && { usage; };
    case "$flag" in
        c)
            echo "RUNNING PROCESS: " $PROCESS
            exit 0;;
        t)
            : ;; # noop
        -)
            break;;
    esac
done
shift $(( OPTIND-1 )); OPTIND=1

# http://aplawrence.com/Unix/getopts.html
#    If an argument is not given for a flag that needs one, "$flag" gets set to
#    ":" and OPTARG has the misused flag. If an unknown argument is given, a
#    "?" is put in "$flag", and OPTARG again has the unrecognized flag.


# get PID
PID=$(echo $PROCESS|cut -d\  -f 1)
echo "PID: " $PID


# toggle
if [ $ENABLED -eq 1 ]; then

    echo "Stopping HDFS tunnel with PID: '$PID'"
    sh -x -c "kill -9 $PID"

else

    sh -x -c "ssh -ND $HDFS_PORT $HDFS_USER@$HDFS_HOST &"
    PID=$(ps -u $USER -eo pid,command |grep 'ssh'|grep $HDFS_HOST|grep -- '-ND')
    PID=$(echo $PID|cut -d\  -f 1)
    echo "Started HDFS tunnel with PID: '$PID'"

fi


#
exit;
#


